CREATE USER IF NOT EXISTS 'remrob'@'%' IDENTIFIED BY 'soeinmisst';
GRANT SELECT, INSERT, UPDATE, DELETE ON *.* TO 'remrob'@'%';
GRANT CREATE, DROP, INDEX, ALTER, REFERENCES ON *.* TO remrob@'%';
FLUSH PRIVILEGES;